import { Edit3, Eye, EyeOff, Trash2 } from "lucide-react"
import { Link } from "react-router-dom"
import { useMutation, useQueryClient } from "@tanstack/react-query"
import { videoApi } from "../../api/video.api"

export function UploadedVideosTable({ videos = [] }) {
  const client = useQueryClient()
  const refresh = () => { client.invalidateQueries({ queryKey: ["dashboard-stats"] }); client.invalidateQueries({ queryKey: ["dashboard-videos"] }); client.invalidateQueries({ queryKey: ["videos"] }) }
  const publish = useMutation({ mutationFn: (id) => videoApi.togglePublish(id), onSuccess: refresh })
  const remove = useMutation({ mutationFn: (id) => videoApi.remove(id), onSuccess: refresh })
  if (!videos.length) return <p className="rounded-lg border border-dashed border-line p-8 text-center text-sm text-muted">No uploaded videos yet.</p>
  return <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-line text-xs uppercase tracking-wide text-muted"><tr><th className="px-3 py-3 font-medium">Video</th><th className="px-3 py-3 font-medium">Visibility</th><th className="px-3 py-3 font-medium">Views</th><th className="px-3 py-3 font-medium">Published</th><th className="px-3 py-3 text-right font-medium">Actions</th></tr></thead><tbody className="divide-y divide-line">{videos.map((video) => <tr key={video._id} className="group"><td className="px-3 py-4"><div className="flex max-w-sm items-center gap-3"><img src={video.thumbnail} alt="" className="h-14 w-24 shrink-0 rounded object-cover" /><Link to={`/watch/${video._id}`} className="truncate font-semibold hover:text-accent">{video.title}</Link></div></td><td className="px-3 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${video.isPublished ? "bg-white text-ink" : "bg-line text-muted"}`}>{video.isPublished ? "Published" : "Unpublished"}</span></td><td className="px-3 py-4 text-muted">{(video.views || 0).toLocaleString()}</td><td className="px-3 py-4 text-muted">{new Date(video.createdAt).toLocaleDateString()}</td><td className="px-3 py-4"><div className="flex justify-end gap-1"><Link to={`/studio/videos/${video._id}/edit`} className="rounded p-2 text-muted hover:bg-line hover:text-white" aria-label="Edit video"><Edit3 size={16} /></Link><button onClick={() => publish.mutate(video._id)} disabled={publish.isPending} className="rounded p-2 text-muted hover:bg-line hover:text-white" aria-label={video.isPublished ? "Unpublish video" : "Publish video"}>{video.isPublished ? <EyeOff size={16} /> : <Eye size={16} />}</button><button onClick={() => { if (window.confirm("Delete this video permanently?")) remove.mutate(video._id) }} disabled={remove.isPending} className="rounded p-2 text-muted hover:bg-line hover:text-accent" aria-label="Delete video"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div>
}
