import { Plus } from "lucide-react"
import { useState } from "react"
import { useAuthStore } from "../stores/authStore"
import { useUserPlaylists, useSocialMutation } from "../hooks/useSocialData"
import { Modal } from "../components/social/Modal"
import { PlaylistForm } from "../components/social/PlaylistForm"
import { PlaylistCard } from "../components/social/PlaylistCard"
import { playlistsApi } from "../api/playlists.api"

export function PlaylistsPage() { const user = useAuthStore((state) => state.user); const { data: playlists = [], isLoading, isError } = useUserPlaylists(user?._id); const { queryClient } = useSocialMutation("playlists"); const [modal, setModal] = useState(null); const save = async () => { setModal(null); await queryClient.invalidateQueries({ queryKey: ["playlists", user?._id] }) }; const remove = async (playlist) => { if (!window.confirm(`Delete ${playlist.name}?`)) return; await playlistsApi.remove(playlist._id); await queryClient.invalidateQueries({ queryKey: ["playlists", user?._id] }) }; return <section className="mx-auto max-w-7xl space-y-7 p-5 md:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-accent">Your library</p><h1 className="mt-2 text-3xl font-bold">Playlists</h1><p className="mt-2 text-muted">Collect videos into a queue worth returning to.</p></div><button onClick={() => setModal({ type: "create" })} className="flex items-center gap-2 rounded-lg bg-accent px-4 py-2.5 text-sm font-bold hover:bg-accent-hover"><Plus size={17} /> New playlist</button></div>{isLoading && <p className="text-muted">Loading playlists...</p>}{isError && <p className="text-sm text-accent">Unable to load playlists.</p>}{!isLoading && !isError && <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{playlists.map((playlist) => <PlaylistCard key={playlist._id} playlist={playlist} onEdit={(item) => setModal({ type: "edit", playlist: item })} onDelete={remove} />)}</div>}{!isLoading && !isError && !playlists.length && <p className="rounded-xl border border-dashed border-line p-10 text-center text-muted">Create your first playlist.</p>}{modal && <Modal title={modal.type === "edit" ? "Edit playlist" : "Create playlist"} onClose={() => setModal(null)}><PlaylistForm playlist={modal.playlist} onSaved={save} onCancel={() => setModal(null)} /></Modal>}</section> }
