import { Link, useNavigate } from "react-router-dom"
import { useForm } from "react-hook-form"
import { FormField } from "../components/ui/FormField"
import { useAuthStore } from "../stores/authStore"
import { getAuthErrorMessage } from "../utils/authError"

export function RegisterPage() {
  const navigate = useNavigate(); const registerUser = useAuthStore((state) => state.register); const { register, handleSubmit, setError, watch, formState: { errors, isSubmitting } } = useForm({ mode: "onBlur" })
  const submit = async (values) => { try { const formData = new FormData(); Object.entries(values).forEach(([key, value]) => { if (key === "avatar") formData.append(key, value[0]); else if (key !== "confirmPassword") formData.append(key, value) }); await registerUser(formData); navigate("/", { replace: true }) } catch (error) { setError("root.server", { message: getAuthErrorMessage(error, "Unable to create account.") }) } }
  return <main className="grid min-h-screen place-items-center bg-ink p-5"><div className="w-full max-w-md rounded-xl border border-line bg-surface p-7"><div className="mb-7 text-center"><div className="mx-auto mb-4 grid h-12 w-12 place-items-center rounded-lg bg-accent text-xl font-black">S</div><h1 className="text-2xl font-bold">Create your account</h1><p className="mt-2 text-sm text-muted">Start building your channel on StreamCore.</p></div><form onSubmit={handleSubmit(submit)} noValidate className="space-y-4"><FormField label="Full name" autoComplete="name" {...register("fullName", { required: "Enter your name" })} error={errors.fullName?.message} /><FormField label="Username" autoComplete="username" {...register("username", { required: "Choose a username", minLength: { value: 3, message: "Use at least 3 characters" } })} error={errors.username?.message} /><FormField label="Email" type="email" autoComplete="email" {...register("email", { required: "Enter your email", pattern: { value: /^\S+@\S+\.\S+$/, message: "Enter a valid email" } })} error={errors.email?.message} /><FormField label="Password" type="password" autoComplete="new-password" {...register("password", { required: "Create a password", minLength: { value: 8, message: "Use at least 8 characters" } })} error={errors.password?.message} /><FormField label="Confirm password" type="password" autoComplete="new-password" {...register("confirmPassword", { required: "Confirm your password", validate: (value) => value === watch("password") || "Passwords do not match" })} error={errors.confirmPassword?.message} /><label className="block space-y-2 text-sm font-medium"><span>Avatar</span><input type="file" accept="image/jpeg,image/png,image/webp" {...register("avatar", { required: "Choose an avatar", validate: (files) => files?.[0]?.size <= 5 * 1024 * 1024 || "Avatar must be 5 MB or smaller" })} className="block w-full text-sm text-muted file:mr-3 file:rounded file:border-0 file:bg-line file:px-3 file:py-2 file:text-white" />{errors.avatar && <span className="block text-xs text-accent">{errors.avatar.message}</span>}</label>{errors.root?.server && <p role="alert" className="text-sm text-accent">{errors.root.server.message}</p>}<button disabled={isSubmitting} className="w-full rounded-lg bg-accent px-4 py-3 font-bold hover:bg-accent-hover disabled:cursor-not-allowed disabled:opacity-60">{isSubmitting ? "Creating..." : "Create account"}</button></form><p className="mt-6 text-center text-sm text-muted">Already a member? <Link to="/login" className="font-semibold text-white hover:text-accent">Sign in</Link></p></div></main>
}
