import { Plus } from "lucide-react"
import { useState } from "react"
import { useAuthStore } from "../stores/authStore"
import { useUserTweets, useSocialMutation, useTweetLike } from "../hooks/useSocialData"
import { tweetsApi } from "../api/tweets.api"
import { Modal } from "../components/social/Modal"
import { TweetForm } from "../components/social/TweetForm"
import { TweetCard } from "../components/social/TweetCard"

export function TweetFeedPage() { const user = useAuthStore((state) => state.user); const { data: tweets = [], isLoading, isError } = useUserTweets(user?._id); const { queryClient } = useSocialMutation("tweets"); const tweetLike = useTweetLike(); const [modal, setModal] = useState(null); const save = async () => { setModal(null); queryClient.invalidateQueries({ queryKey: ["tweets", user?._id] }) }; const remove = async (tweet) => { if (!window.confirm("Delete this tweet?")) return; await tweetsApi.remove(tweet._id); queryClient.invalidateQueries({ queryKey: ["tweets", user?._id] }) }; return <section className="mx-auto max-w-2xl space-y-6 p-5 md:p-8"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-accent">Community</p><h1 className="mt-2 text-3xl font-bold">Your tweet feed</h1></div><button onClick={() => setModal({ type: "create" })} className="flex items-center gap-2 rounded-lg bg-accent px-4 py-2.5 text-sm font-bold hover:bg-accent-hover"><Plus size={17} /> Tweet</button></div>{isLoading && <p className="text-muted">Loading tweets...</p>}{isError && <p className="text-sm text-accent">Unable to load tweets.</p>}{!isLoading && !isError && <div className="space-y-4">{tweets.length ? tweets.map((tweet) => <TweetCard key={tweet._id} tweet={{ ...tweet, owner: tweet.owner || user }} currentUserId={user?._id} onLike={(id) => tweetLike.mutate(id)} onEdit={(item) => setModal({ type: "edit", tweet: item })} onDelete={remove} />) : <p className="rounded-xl border border-dashed border-line p-10 text-center text-muted">No tweets yet. Share an update with your audience.</p>}</div>}{modal && <Modal title={modal.type === "edit" ? "Edit tweet" : "Create tweet"} onClose={() => setModal(null)}><TweetForm tweet={modal.tweet} onSaved={save} onCancel={() => setModal(null)} /></Modal>}</section> }
